# Generated by Django 4.2.5 on 2023-10-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="表紙画像"
            ),
        ),
    ]
